version: '3.5'
services:
    smartdns-over-wireguard:
        container_name: smartdns-over-wireguard
        environment:
            - VPN_SERVER_IP=10.10.0.254
        ports:
            - 51820:51820/udp
        volumes:
            - ./configs/wireguard/wg0.conf:/etc/wireguard/wg0.conf:ro
            - ./configs/dnsmasq/:/tmp/dnsmasq/:ro
        cap_add:
            - NET_ADMIN
        restart: unless-stopped
        image: 'cwlu2001/smartdns-over-wireguard:latest'